version: '3.4'

services:
  identityserverwithaspnetidentity:
    image: ${DOCKER_REGISTRY}identityserverwithaspnetidentity
    build:
      context: .
      dockerfile: src/IdentityServerWithAspNetIdentity/Dockerfile
